### ISSUE TITLE
大佬，两年没更新了，什么时候更新一下啊

### ISSUE THREAD

**Issue by lldfire** [EVA-JianJun/AzurLanePng#1]
大佬，两年没更新了，什么时候更新一下啊

**Comment by EVA-JianJun** [comment]
@lldfire 游戏都被我删了, 我也是按照别人的教程把APK中的内容给提取出来而已, 不难的, 只是需要点工作量, 你看看瞧你自己能不能自己搞, 搞定了给我提个PR嘛 233, 或者等我过几天有时间再弄我更新下

**Comment by lldfire** [comment]
我没有windows 系统的电脑，那些提取工具用不了

**Comment by lldfire** [comment]
@EVA-JianJun 我没有windows 系统的电脑，我看的那些提取工具都用不了

**Comment by EVA-JianJun** [comment]
@lldfire 已更新
